### ISSUE TITLE
Incorrect snippet closing tag

### ISSUE THREAD

**Issue by alfiehd** [cjhowe7/laravel-blade-vscode#2]
@cjhowe7 the snippet for foreach does not have the correct closing endforeach and instead endfor.

Example:
```
@foreach($posts as $post)
    {{ $post->title }}
@endfor
```

but should read as

```
@foreach($posts as $post)
    {{ $post->title }}
@endforeach
```

**Comment by cjhowe7** [comment]
Hey, you're right! Feel free to make a pull request if you have fixed this.
